// <auto-generated />
using Labb2_Avancerad.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb2_Avancerad.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220926082523_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Labb2_Avancerad.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"), 1L, 1);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Toys & Computers"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Computers, Games & Beauty"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Books"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Sports & Grocery"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Kids"
                        });
                });

            modelBuilder.Entity("Labb2_Avancerad.Models.Personal", b =>
                {
                    b.Property<int>("PersonalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalId"), 1L, 1);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("PersonalId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Personals");

                    b.HasData(
                        new
                        {
                            PersonalId = 1,
                            Adress = "49253 Okey Run, Sylvesterton, China",
                            DepartmentId = 5,
                            Email = "Iliana_Kreiger@hotmail.com",
                            FirstName = "Jayson",
                            Gender = "Male",
                            LastName = "Collier",
                            PhoneNumber = "951.492.4453 x57865",
                            Salary = 1740.3800000000001
                        },
                        new
                        {
                            PersonalId = 2,
                            Adress = "16046 Edgardo Lakes, Port Tomasstad, Belgium",
                            DepartmentId = 4,
                            Email = "Tristian.Macejkovic@hotmail.com",
                            FirstName = "Turner",
                            Gender = "Male",
                            LastName = "Stoltenberg",
                            PhoneNumber = "(202) 858-5488",
                            Salary = 4836.21
                        },
                        new
                        {
                            PersonalId = 3,
                            Adress = "0830 Moses Ridge, New Willafurt, Vietnam",
                            DepartmentId = 2,
                            Email = "Amalia.Fadel@gmail.com",
                            FirstName = "Kathlyn",
                            Gender = "Male",
                            LastName = "Tremblay",
                            PhoneNumber = "(310) 916-7522",
                            Salary = 5104.8699999999999
                        },
                        new
                        {
                            PersonalId = 4,
                            Adress = "508 Olen Square, Leannonmouth, Papua New Guinea",
                            DepartmentId = 1,
                            Email = "Raymundo.Dibbert@yahoo.com",
                            FirstName = "Mckayla",
                            Gender = "Male",
                            LastName = "Kulas",
                            PhoneNumber = "1-919-559-1151 x78400",
                            Salary = 3533.5599999999999
                        },
                        new
                        {
                            PersonalId = 5,
                            Adress = "50401 Heller Shore, South Clovis, Azerbaijan",
                            DepartmentId = 1,
                            Email = "Zora.Bartoletti@yahoo.com",
                            FirstName = "Albin",
                            Gender = "Female",
                            LastName = "Satterfield",
                            PhoneNumber = "903.629.6148 x121",
                            Salary = 2147.4699999999998
                        },
                        new
                        {
                            PersonalId = 6,
                            Adress = "02789 Farrell Gateway, West Georgette, United States of America",
                            DepartmentId = 2,
                            Email = "Kennedy.Waters@yahoo.com",
                            FirstName = "Chris",
                            Gender = "Male",
                            LastName = "Lakin",
                            PhoneNumber = "509.783.8130 x14600",
                            Salary = 6797.0500000000002
                        },
                        new
                        {
                            PersonalId = 7,
                            Adress = "3206 Mayert Extension, Strosinstad, Falkland Islands (Malvinas)",
                            DepartmentId = 5,
                            Email = "Dora_Skiles@gmail.com",
                            FirstName = "Monserrat",
                            Gender = "Female",
                            LastName = "Yost",
                            PhoneNumber = "448.411.3624 x341",
                            Salary = 4640.7799999999997
                        },
                        new
                        {
                            PersonalId = 8,
                            Adress = "61239 Leopold Valley, Chloeberg, Peru",
                            DepartmentId = 3,
                            Email = "Dale5@gmail.com",
                            FirstName = "Dorcas",
                            Gender = "Female",
                            LastName = "Beer",
                            PhoneNumber = "1-708-308-6606 x60813",
                            Salary = 4826.1599999999999
                        },
                        new
                        {
                            PersonalId = 9,
                            Adress = "2487 Clint Cove, West Magnus, Brunei Darussalam",
                            DepartmentId = 3,
                            Email = "Aimee_Christiansen@gmail.com",
                            FirstName = "Adeline",
                            Gender = "Male",
                            LastName = "Cormier",
                            PhoneNumber = "808-518-2566",
                            Salary = 5813.9899999999998
                        },
                        new
                        {
                            PersonalId = 10,
                            Adress = "09404 Hobart Manor, Tressafurt, Madagascar",
                            DepartmentId = 5,
                            Email = "Emmitt75@hotmail.com",
                            FirstName = "Harley",
                            Gender = "Female",
                            LastName = "Trantow",
                            PhoneNumber = "636.545.4591 x801",
                            Salary = 6210.5299999999997
                        },
                        new
                        {
                            PersonalId = 11,
                            Adress = "981 Otha Highway, Bartonfurt, China",
                            DepartmentId = 1,
                            Email = "Brielle.Boyle82@gmail.com",
                            FirstName = "Rebekah",
                            Gender = "Female",
                            LastName = "Treutel",
                            PhoneNumber = "(737) 752-8934 x1458",
                            Salary = 8293.2099999999991
                        },
                        new
                        {
                            PersonalId = 12,
                            Adress = "139 D'Amore Junctions, Bartholomeville, Guyana",
                            DepartmentId = 4,
                            Email = "Maxwell27@yahoo.com",
                            FirstName = "Landen",
                            Gender = "Male",
                            LastName = "Farrell",
                            PhoneNumber = "(247) 957-8786 x59580",
                            Salary = 1861.5599999999999
                        },
                        new
                        {
                            PersonalId = 13,
                            Adress = "39995 Eric Land, Anthonyport, Jamaica",
                            DepartmentId = 4,
                            Email = "Luella_Fadel@yahoo.com",
                            FirstName = "Jimmie",
                            Gender = "Female",
                            LastName = "Wisoky",
                            PhoneNumber = "501-390-4319 x3805",
                            Salary = 3319.2600000000002
                        },
                        new
                        {
                            PersonalId = 14,
                            Adress = "455 Jacey Terrace, Port Blanchemouth, Djibouti",
                            DepartmentId = 4,
                            Email = "Urban23@hotmail.com",
                            FirstName = "Brennon",
                            Gender = "Male",
                            LastName = "Beer",
                            PhoneNumber = "(971) 213-8862 x866",
                            Salary = 3889.2800000000002
                        },
                        new
                        {
                            PersonalId = 15,
                            Adress = "955 Rath Hill, Lednerstad, Iran",
                            DepartmentId = 4,
                            Email = "Leland.Hodkiewicz@gmail.com",
                            FirstName = "Lavonne",
                            Gender = "Male",
                            LastName = "Kulas",
                            PhoneNumber = "1-949-702-8545 x2656",
                            Salary = 4018.25
                        },
                        new
                        {
                            PersonalId = 16,
                            Adress = "014 Hoppe Circle, West Madelynview, Trinidad and Tobago",
                            DepartmentId = 4,
                            Email = "Pierre.Heller36@yahoo.com",
                            FirstName = "Bart",
                            Gender = "Male",
                            LastName = "Gaylord",
                            PhoneNumber = "958.323.6335 x593",
                            Salary = 9372.2399999999998
                        },
                        new
                        {
                            PersonalId = 17,
                            Adress = "745 Alana Pine, East Thelmaland, Fiji",
                            DepartmentId = 3,
                            Email = "Wiley85@gmail.com",
                            FirstName = "Austin",
                            Gender = "Female",
                            LastName = "Reichel",
                            PhoneNumber = "350-791-6141",
                            Salary = 2984.9699999999998
                        },
                        new
                        {
                            PersonalId = 18,
                            Adress = "6264 Kadin Manor, Mattfurt, Vanuatu",
                            DepartmentId = 1,
                            Email = "Nels.Schimmel69@yahoo.com",
                            FirstName = "Ebony",
                            Gender = "Female",
                            LastName = "O'Kon",
                            PhoneNumber = "(234) 602-3022 x50027",
                            Salary = 9546.0799999999999
                        },
                        new
                        {
                            PersonalId = 19,
                            Adress = "70576 Victoria Land, South Helgaville, Colombia",
                            DepartmentId = 1,
                            Email = "Arno.Lehner@yahoo.com",
                            FirstName = "Tierra",
                            Gender = "Male",
                            LastName = "O'Reilly",
                            PhoneNumber = "1-411-231-7116",
                            Salary = 1485.25
                        },
                        new
                        {
                            PersonalId = 20,
                            Adress = "15813 Eino Island, Murrayborough, Ghana",
                            DepartmentId = 1,
                            Email = "Gaylord_Bergstrom62@yahoo.com",
                            FirstName = "Gerhard",
                            Gender = "Male",
                            LastName = "Gulgowski",
                            PhoneNumber = "1-374-810-9587",
                            Salary = 1232.4000000000001
                        });
                });

            modelBuilder.Entity("Labb2_Avancerad.Models.Personal", b =>
                {
                    b.HasOne("Labb2_Avancerad.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
